export const fitnessProducts = [
  {
    name: "Whey Protein",
    category: "Supplement",
    costInRupees: 3000,
    description: "A high-quality protein powder to aid in muscle recovery and growth.",
    imageadd1: '/equipimages/Whey Protein1.jpg',
    imageadd2: '/equipimages/Whey Protein2.jpg',
    imageadd3: '/equipimages/Whey Protein3.jpg',
    rating: 3.5,
    discount: 54,
    isCart: false,
    longDescription: "Whey Protein is a fast-digesting protein derived from milk, known for its ability to quickly deliver amino acids to muscles after workouts. It is ideal for muscle recovery, repair, and overall growth, making it a staple in the diet of athletes and fitness enthusiasts. This supplement helps in meeting daily protein needs, supports lean muscle mass, and enhances post-workout recovery. It can be consumed as a shake, added to smoothies, or used in baking to boost protein intake throughout the day."
  },
  {
    name: "Creatine Monohydrate",
    category: "Supplement",
    costInRupees: 1500,
    description: "Boosts strength and power output for high-intensity workouts.",
    imageadd1: '/equipimages/Creatine Monohydrate1.jpg',
    imageadd2: '/equipimages/Creatine Monohydrate2.jpg',
    imageadd3: '/equipimages/Creatine Monohydrate3.jpg',
    rating: 3.5,
    discount: 54,
    isCart: false,
    longDescription: "Creatine Monohydrate is one of the most researched and effective supplements for improving strength and performance in high-intensity activities such as weightlifting, sprinting, and explosive sports. It works by replenishing the body's ATP stores, providing energy for short bursts of exercise. Regular supplementation helps increase muscle strength, improve endurance, and enhance workout capacity. Creatine is ideal for athletes and bodybuilders looking to maximize their power and performance during training."
  },
  {
    name: "Dumbbells (5kg)",
    category: "Gym Equipment",
    costInRupees: 1200,
    description: "Compact 5kg dumbbells for strength training at home or the gym.",
    imageadd1: '/equipimages/Dumbbells (5kg)1.jpg',
    imageadd2: '/equipimages/Dumbbells (5kg)2.jpg',
    imageadd3: '/equipimages/Dumbbells (5kg)3.jpg',
    rating: 3.5,
    discount: 54,
    isCart: false,
    longDescription: "These 5kg dumbbells are a versatile piece of gym equipment that can be used for a variety of strength training exercises, including curls, presses, and rows. Compact and easy to store, they are perfect for home workouts or adding to a personal gym setup. Whether you're a beginner or experienced lifter, these dumbbells allow you to progressively build strength, tone muscles, and improve overall fitness. Their ergonomic design ensures a comfortable grip, minimizing strain during exercises."
  },
  {
    name: "BCAA",
    category: "Supplement",
    costInRupees: 1800,
    description: "Branched-Chain Amino Acids to reduce muscle fatigue and enhance recovery.",
    imageadd1: '/equipimages/BCAA1.jpg',
    imageadd2: '/equipimages/BCAA2.jpg',
    imageadd3: '/equipimages/BCAA3.jpg',
    rating: 3.5,
    discount: 54,
    isCart: false,
    longDescription: "BCAA (Branched-Chain Amino Acids) are essential nutrients that help in reducing muscle breakdown during intense exercise. Comprising leucine, isoleucine, and valine, BCAAs are known for their ability to preserve muscle glycogen stores, reduce muscle soreness, and speed up recovery post-exercise. They are especially beneficial for endurance athletes and those engaging in prolonged training sessions. Taken before, during, or after a workout, BCAAs can enhance performance and prevent fatigue."
  },
  {
    name: "Kettlebell (10kg)",
    category: "Gym Equipment",
    costInRupees: 2500,
    description: "A 10kg kettlebell ideal for dynamic and full-body strength workouts.",
    imageadd1: '/equipimages/Kettlebell (10kg)1.jpg',
    imageadd2: '/equipimages/Kettlebell (10kg)2.jpg',
    imageadd3: '/equipimages/Kettlebell (10kg)3.jpg',
    rating: 3.5,
    discount: 54,
    isCart: false,
    longDescription: "This 10kg kettlebell is a perfect tool for dynamic, functional workouts that engage multiple muscle groups at once. From swings and snatches to squats and presses, kettlebell exercises improve strength, flexibility, and cardiovascular endurance. The weight is ideal for beginners as well as advanced fitness enthusiasts looking for a full-body workout. The ergonomic handle provides a comfortable and secure grip, while the compact design allows for easy storage and portability."
  },
  {
    name: "Yoga Mat",
    category: "Gym Equipment",
    costInRupees: 800,
    description: "A non-slip mat perfect for yoga, stretching, and pilates exercises.",
    imageadd1: '/equipimages/Yoga Mat1.jpg',
    imageadd2: '/equipimages/Yoga Mat2.jpg',
    imageadd3: '/equipimages/Yoga Mat3.jpg',
    rating: 3.5,
    discount: 54,
    isCart: false,
    longDescription: "This yoga mat provides a comfortable, non-slip surface for all types of exercises, including yoga, pilates, and stretching routines. The cushioned support helps protect joints and prevent injuries, while the textured surface ensures a firm grip, even during the most challenging poses. Lightweight and portable, the mat can be rolled up for easy transport, making it an excellent choice for both home practice and studio sessions. Its durability and comfort make it a staple for any fitness enthusiast."
  },
  {
    name: "Fish Oil Capsules",
    category: "Supplement",
    costInRupees: 900,
    description: "Omega-3 capsules that support joint health and improve heart function.",
    imageadd1: '/equipimages/Fish Oil Capsules1.jpg',
    imageadd2: '/equipimages/Fish Oil Capsules2.jpg',
    imageadd3: '/equipimages/Fish Oil Capsules3.jpg',
    rating: 3.5,
    discount: 54,
    isCart: false,
    longDescription: "Fish Oil Capsules are a rich source of Omega-3 fatty acids, which are essential for maintaining heart health, reducing inflammation, and supporting joint mobility. These capsules contain EPA and DHA, two critical components that contribute to cardiovascular wellness and improved cholesterol levels. Regular consumption of fish oil can also help reduce muscle soreness after intense workouts and promote overall wellness. Ideal for anyone looking to improve their diet and support their body's natural functions."
  },
  {
    name: "Resistance Bands Set",
    category: "Gym Equipment",
    costInRupees: 1000,
    description: "A set of resistance bands with multiple tension levels for strength workouts.",
    imageadd1: '/equipimages/Resistance Bands Set1.jpg',
    imageadd2: '/equipimages/Resistance Bands Set2.jpg',
    imageadd3: '/equipimages/Resistance Bands Set3.jpg',
    rating: 3.5,
    discount: 54,
    isCart: false,
    longDescription: "This set of resistance bands is perfect for strength training, rehabilitation, and improving flexibility. Each band offers a different level of tension, allowing for a variety of exercises that target different muscle groups. Whether you're a beginner or an advanced athlete, these bands can be used for warm-ups, resistance workouts, or recovery exercises. The compact and lightweight design makes them portable and easy to use anywhere, from home to the gym."
  },
  {
    name: "Glutamine",
    category: "Supplement",
    costInRupees: 1300,
    description: "Supports muscle recovery and boosts the immune system after intense exercise.",
    imageadd1: '/equipimages/Glutamine1.jpg',
    imageadd2: '/equipimages/Glutamine2.jpg',
    imageadd3: '/equipimages/Glutamine3.jpg',
    rating: 3.5,
    discount: 54,
    isCart: false,
    longDescription: "Glutamine is an essential amino acid that plays a crucial role in muscle recovery and immune function. After intense physical activity, glutamine levels in the body are depleted, which can slow recovery and weaken immune defense. Supplementing with glutamine helps speed up recovery, reduce muscle soreness, and improve gut health, which is vital for immune strength. This makes it a valuable addition to the regimen of athletes looking to enhance recovery and overall performance."
  },
  {
    name: "Adjustable Dumbbells (2-20kg)",
    category: "Gym Equipment",
    costInRupees: 8000,
    description: "Versatile adjustable dumbbells ranging from 2kg to 20kg for a variety of workouts.",
    imageadd1: '/equipimages/Adjustable Dumbbells (2-20kg)1.jpg',
    imageadd2: '/equipimages/Adjustable Dumbbells (2-20kg)2.jpg',
    imageadd3: '/equipimages/Adjustable Dumbbells (2-20kg)3.jpg',
    rating: 3.5,
    discount: 54,
    isCart: false,
    longDescription: "Adjustable Dumbbells offer a space-saving, versatile solution for a wide range of strength training exercises. With weight settings from 2kg to 20kg, these dumbbells allow users to quickly change resistance levels without needing multiple sets of weights. Perfect for targeting various muscle groups, from arms and shoulders to legs and core, these adjustable dumbbells provide all the flexibility of a full dumbbell set in a compact form. Ideal for both beginners and experienced lifters who want to perform a variety of exercises without the clutter."
  },
  {
      name: "Pre-Workout",
      category: "Supplement",
      costInRupees: 2200,
      description: "An energy-boosting supplement to enhance focus and endurance.",
      imageadd1: '/equipimages/Pre-Workout1.jpg',
      imageadd2: '/equipimages/Pre-Workout2.jpg',
      imageadd3: '/equipimages/Pre-Workout3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Pre-Workout supplements are designed to provide an energy boost, enhance focus, and improve endurance during intense exercise. Packed with ingredients like caffeine, beta-alanine, and citrulline malate, pre-workouts increase blood flow, delay muscle fatigue, and sharpen mental focus. Perfect for individuals looking to improve workout intensity, this supplement can be taken 30 minutes before exercise for optimal performance, ensuring that you have the stamina to push through challenging workouts."
    },
    {
      name: "Casein Protein",
      category: "Supplement",
      costInRupees: 3200,
      description: "Slow-digesting protein that promotes muscle repair while sleeping.",
      imageadd1: '/equipimages/Casein Protein1.jpg',
      imageadd2: '/equipimages/Casein Protein2.jpg',
      imageadd3: '/equipimages/Casein Protein3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Casein Protein is a slow-digesting milk protein that provides a sustained release of amino acids, making it ideal for muscle recovery and growth during sleep. It helps in reducing muscle breakdown, supports lean muscle mass, and keeps the body nourished with essential proteins over an extended period. Perfect as a bedtime shake, casein is popular among athletes who want to ensure that their muscles are fed throughout the night, aiding recovery and minimizing overnight muscle breakdown."
    },
    {
      name: "Foam Roller",
      category: "Gym Equipment",
      costInRupees: 1000,
      description: "A tool for muscle recovery, massage, and improving flexibility.",
      imageadd1: '/equipimages/Foam Roller1.jpg',
      imageadd2: '/equipimages/Foam Roller2.jpg',
      imageadd3: '/equipimages/Foam Roller3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Foam Rollers are excellent tools for self-myofascial release, improving blood flow, and speeding up muscle recovery after intense exercise. Rolling out muscles with a foam roller helps break up scar tissue, reduce stiffness, and improve overall flexibility. This tool is great for reducing soreness, especially after strength training or cardio sessions, and can also be used for core strengthening exercises. It’s portable and ideal for home or gym use, providing an effective way to relieve muscle tension."
    },
    {
      name: "Jump Rope",
      category: "Gym Equipment",
      costInRupees: 500,
      description: "A lightweight jump rope ideal for cardio and endurance training.",
      imageadd1: '/equipimages/Jump Rope1.jpg',
      imageadd2: '/equipimages/Jump Rope2.jpg',
      imageadd3: '/equipimages/Jump Rope3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Jump ropes are one of the best tools for cardiovascular training, helping improve endurance, agility, and coordination. This lightweight and adjustable jump rope is perfect for both beginners and advanced athletes. Regular jump rope sessions help burn calories, increase stamina, and improve overall cardiovascular health. Compact and portable, it can be used anywhere, making it an excellent choice for quick, effective cardio workouts at home, outdoors, or in the gym."
    },
    {
      name: "L-Carnitine",
      category: "Supplement",
      costInRupees: 1200,
      description: "A supplement that helps convert fat into energy during exercise.",
      imageadd1: '/equipimages/L-Carnitine1.jpg',
      imageadd2: '/equipimages/L-Carnitine2.jpg',
      imageadd3: '/equipimages/L-Carnitine3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "L-Carnitine is a naturally occurring amino acid that plays a vital role in the transportation of fatty acids into the cells to be burned as energy. By supporting fat metabolism, L-Carnitine helps enhance endurance, improve energy levels, and accelerate fat loss during workouts. This makes it an ideal supplement for individuals focused on weight management and performance. Regular use of L-Carnitine can improve stamina, reduce fatigue, and enhance post-exercise recovery."
    },
    {
      name: "Ankle Weights (2kg)",
      category: "Gym Equipment",
      costInRupees: 800,
      description: "Adjustable ankle weights for adding resistance to lower body exercises.",
      imageadd1: '/equipimages/Ankle Weights (2kg)1.jpg',
      imageadd2: '/equipimages/Ankle Weights (2kg)2.jpg',
      imageadd3: '/equipimages/Ankle Weights (2kg)3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Ankle Weights are a great way to add resistance to your lower body exercises, including leg lifts, squats, and lunges. These adjustable 2kg ankle weights can also be used during walking, running, or daily activities to increase calorie burn and build muscle strength in the legs. Ideal for improving overall endurance and muscle toning, they are easy to strap on and comfortable for extended use. Suitable for home workouts or gym sessions, they are a versatile tool for fitness enthusiasts of all levels."
    },
    {
      name: "Multivitamin",
      category: "Supplement",
      costInRupees: 500,
      description: "A comprehensive multivitamin for daily health and wellness support.",
      imageadd1: '/equipimages/Multivitamin1.jpg',
      imageadd2: '/equipimages/Multivitamin2.jpg',
      imageadd3: '/equipimages/Multivitamin3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Multivitamins provide a daily dose of essential vitamins and minerals to support overall health, immunity, and energy levels. They are especially beneficial for individuals with demanding workout schedules, ensuring that they get the necessary nutrients for muscle repair, bone health, and energy production. Formulated with key ingredients like Vitamin C, D, B-complex, and minerals like zinc and magnesium, a multivitamin helps fill nutritional gaps and supports optimal body function, especially for those engaged in intense physical activities."
    },
    {
      name: "Medicine Ball (6kg)",
      category: "Gym Equipment",
      costInRupees: 2000,
      description: "A 6kg medicine ball for functional strength training and core exercises.",
      imageadd1: '/equipimages/Medicine Ball (6kg)1.jpg',
      imageadd2: '/equipimages/Medicine Ball (6kg)2.jpg',
      imageadd3: '/equipimages/Medicine Ball (6kg)3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "The 6kg medicine ball is perfect for functional strength training, core strengthening, and explosive power exercises. It can be used for a wide range of exercises, such as slams, wall throws, and partner drills, providing a fun and effective way to improve strength, coordination, and balance. The ball’s sturdy design ensures durability during high-impact workouts, and its versatility makes it an essential piece of equipment for both beginners and advanced athletes. Great for improving overall athletic performance."
    },
    {
      name: "Hand Grippers",
      category: "Gym Equipment",
      costInRupees: 400,
      description: "A tool for strengthening grip, forearms, and hand muscles.",
      imageadd1: '/equipimages/Hand Grippers1.jpg',
      imageadd2: '/equipimages/Hand Grippers2.jpg',
      imageadd3: '/equipimages/Hand Grippers3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Hand Grippers are excellent for building grip strength, forearm muscles, and overall hand dexterity. Regular use of hand grippers helps improve grip endurance, which is essential for weightlifting, climbing, and other sports that require a strong grip. Lightweight and portable, hand grippers can be used anywhere and are a great addition to any strength training routine. They help reduce the risk of injuries associated with weak grip strength and improve performance in exercises like deadlifts and pull-ups."
    },
    {
      name: "Protein Bars (Box of 12)",
      category: "Supplement",
      costInRupees: 1200,
      description: "A box of 12 protein bars, perfect for post-workout recovery and snacks.",
      imageadd1: '/equipimages/Protein Bars (Box of 12)1.jpg',
      imageadd2: '/equipimages/Protein Bars (Box of 12)2.jpg',
      imageadd3: '/equipimages/Protein Bars (Box of 12)3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Protein Bars are a convenient and delicious way to meet daily protein needs, providing a quick snack that helps with muscle recovery and growth. Each bar is packed with high-quality protein, essential amino acids, and a balanced mix of carbohydrates and fats, making it ideal for post-workout recovery or as an on-the-go snack. With 12 bars in a box, they are perfect for anyone looking to maintain their protein intake throughout the day while keeping hunger at bay. These bars are also great for those with busy schedules."
    },
    {
      name: "Electrolyte Powder",
      category: "Supplement",
      costInRupees: 700,
      description: "Replenishes electrolytes lost during intense workouts or heat.",
      imageadd1: '/equipimages/Electrolyte Powder1.jpg',
      imageadd2: '/equipimages/Electrolyte Powder2.jpg',
      imageadd3: '/equipimages/Electrolyte Powder3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Electrolyte powder helps to restore the essential salts and minerals lost through sweat during intense exercise or in hot environments. It supports hydration, reduces cramping, and helps maintain energy levels throughout your workout. With a balanced mix of sodium, potassium, magnesium, and calcium, this powder is ideal for athletes, runners, or anyone engaged in endurance activities. Easily mix it with water for a refreshing and replenishing drink to maintain optimal performance."
    },
    {
      name: "Ab Roller",
      category: "Gym Equipment",
      costInRupees: 600,
      description: "A compact tool for building core strength and stability.",
      imageadd1: '/equipimages/Ab Roller1.jpg',
      imageadd2: '/equipimages/Ab Roller2.jpg',
      imageadd3: '/equipimages/Ab Roller3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "The Ab Roller is a simple yet highly effective tool for strengthening the core muscles, including the abs, obliques, and lower back. It helps improve stability, balance, and overall core endurance, making it ideal for both beginners and advanced fitness enthusiasts. By rolling forward and backward, you can engage your entire core while also working your arms and shoulders. Lightweight and portable, the Ab Roller is easy to store and perfect for home or gym use."
    },
    {
      name: "Adjustable Bench",
      category: "Gym Equipment",
      costInRupees: 4500,
      description: "A multi-purpose bench with adjustable settings for versatile workouts.",
      imageadd1: '/equipimages/Adjustable Bench1.jpg',
      imageadd2: '/equipimages/Adjustable Bench2.jpg',
      imageadd3: '/equipimages/Adjustable Bench3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "The Adjustable Bench is an essential piece of gym equipment for strength training, allowing users to perform a wide variety of exercises targeting different muscle groups. The bench can be adjusted to different angles, from flat to incline or decline, to perform exercises like bench presses, dumbbell rows, and sit-ups. With a sturdy frame and comfortable padding, this bench provides the support needed for intense workouts while being durable enough for home gyms or commercial setups."
    },
    {
      name: "ZMA Capsules",
      category: "Supplement",
      costInRupees: 1200,
      description: "A supplement blend of zinc, magnesium, and vitamin B6 to support recovery.",
      imageadd1: '/equipimages/ZMA Capsules1.jpg',
      imageadd2: '/equipimages/ZMA Capsules2.jpg',
      imageadd3: '/equipimages/ZMA Capsules3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "ZMA (Zinc Monomethionine Aspartate, Magnesium Aspartate, and Vitamin B6) is a powerful combination designed to improve recovery, support muscle strength, and enhance sleep quality. It is commonly used by athletes to boost testosterone levels, aid muscle repair, and support immune health. Taking ZMA capsules before bedtime helps improve sleep quality, which is essential for effective recovery after intense workouts. This makes it an excellent supplement for those engaged in regular strength training."
    },
    {
      name: "Treadmill Lubricant",
      category: "Gym Equipment",
      costInRupees: 400,
      description: "A silicone lubricant to maintain the smooth operation of treadmill belts.",
      imageadd1: '/equipimages/Treadmill Lubricant1.jpg',
      imageadd2: '/equipimages/Treadmill Lubricant2.jpg',
      imageadd3: '/equipimages/Treadmill Lubricant3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Treadmill Lubricant helps reduce friction between the treadmill belt and deck, ensuring smooth and quiet operation. Regular lubrication extends the life of the treadmill by reducing wear and tear on the motor and belt. This silicone-based lubricant is easy to apply and is suitable for all treadmill models. It's essential for anyone using treadmills regularly to maintain the equipment's performance and prevent costly repairs."
    },
    {
      name: "Mass Gainer",
      category: "Supplement",
      costInRupees: 2800,
      description: "A high-calorie supplement for muscle growth and weight gain.",
      imageadd1: '/equipimages/Mass Gainer1.jpg',
      imageadd2: '/equipimages/Mass Gainer2.jpg',
      imageadd3: '/equipimages/Mass Gainer3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Mass Gainers are high-calorie supplements designed for individuals looking to increase muscle mass and overall body weight. They provide a balanced mix of proteins, carbohydrates, and fats, along with essential vitamins and minerals, to support muscle recovery and growth. Ideal for hard gainers or anyone who struggles to meet their calorie needs through food alone, mass gainers help increase caloric intake in a convenient way. It’s best consumed post-workout or as a meal replacement for athletes aiming to bulk up."
    },
    {
      name: "Push-Up Bars",
      category: "Gym Equipment",
      costInRupees: 700,
      description: "A pair of bars designed to enhance push-up performance and reduce wrist strain.",
      imageadd1: '/equipimages/Push-Up Bars1.jpg',
      imageadd2: '/equipimages/Push-Up Bars2.jpg',
      imageadd3: '/equipimages/Push-Up Bars3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Push-Up Bars are an excellent tool for enhancing your push-up workout by allowing for a greater range of motion and reducing wrist strain. The ergonomic design promotes better hand positioning, making the exercise more comfortable while targeting chest, shoulder, and arm muscles more effectively. These bars are portable, lightweight, and easy to use at home or in the gym, helping you increase the intensity of your upper-body training routine."
    },
    {
      name: "Compression Socks",
      category: "Gym Equipment",
      costInRupees: 600,
      description: "Socks designed to improve circulation and reduce muscle fatigue.",
      imageadd1: '/equipimages/Compression Socks1.jpg',
      imageadd2: '/equipimages/Compression Socks2.jpg',
      imageadd3: '/equipimages/Compression Socks3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Compression socks are designed to provide graduated pressure to the lower legs, which improves blood circulation, reduces swelling, and minimizes muscle fatigue during or after exercise. They're commonly used by runners, athletes, or anyone on their feet for long periods. Compression socks help in quicker recovery and are especially beneficial after long runs, intense workouts, or during travel. The snug fit ensures comfort and support, making them an essential accessory for active individuals."
    },
    {
      name: "Knee Sleeves",
      category: "Gym Equipment",
      costInRupees: 1500,
      description: "Neoprene sleeves that provide support and warmth to the knees during lifting.",
      imageadd1: '/equipimages/Knee Sleeves1.jpg',
      imageadd2: '/equipimages/Knee Sleeves2.jpg',
      imageadd3: '/equipimages/Knee Sleeves3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Knee Sleeves are designed to provide compression and support to the knee joints during heavy lifting, squats, and high-intensity workouts. Made from durable neoprene, they help improve blood flow, reduce pain and discomfort, and enhance stability, preventing injuries during exercise. Whether you're a weightlifter, crossfitter, or just someone looking for extra knee support, knee sleeves offer the protection and comfort needed to perform at your best. Their ergonomic fit also keeps joints warm and flexible."
    },
    {
      name: "Fitness Tracker",
      category: "Gym Equipment",
      costInRupees: 3000,
      description: "A wearable device to monitor heart rate, steps, calories, and sleep.",
      imageadd1: '/equipimages/Fitness Tracker1.jpg',
      imageadd2: '/equipimages/Fitness Tracker2.jpg',
      imageadd3: '/equipimages/Fitness Tracker3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "A Fitness Tracker is a wearable device that helps monitor your daily physical activity, including heart rate, steps, calories burned, and even sleep patterns. It provides real-time data on your workouts, encouraging you to stay active and achieve your fitness goals. With features like activity reminders, heart rate monitoring, and progress tracking, this device is perfect for both beginners and advanced athletes who want to optimize their performance. It also syncs with mobile apps, making it easy to keep track of your fitness journey."
    },
    {
      name: "TRX Suspension Trainer",
      category: "Gym Equipment",
      costInRupees: 6000,
      description: "A versatile suspension training system for full-body workouts.",
      imageadd1: '/equipimages/TRX Suspension Trainer1.jpg',
      imageadd2: '/equipimages/TRX Suspension Trainer2.jpg',
      imageadd3: '/equipimages/TRX Suspension Trainer3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "The TRX Suspension Trainer utilizes your body weight to provide resistance and allows for hundreds of exercises that improve strength, flexibility, and core stability. It's ideal for all fitness levels, from beginners to professional athletes, offering adjustable resistance and the ability to perform exercises targeting every major muscle group. Portable and easy to set up indoors or outdoors, the TRX is perfect for home workouts or traveling fitness enthusiasts."
    },
    {
      name: "Foam Massage Roller",
      category: "Gym Equipment",
      costInRupees: 800,
      description: "A foam roller with textured surface for deep tissue massage and muscle recovery.",
      imageadd1: '/equipimages/Foam Massage Roller1.jpg',
      imageadd2: '/equipimages/Foam Massage Roller2.jpg',
      imageadd3: '/equipimages/Foam Massage Roller3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "The Foam Massage Roller is designed to target and alleviate muscle tightness, knots, and tension through self-myofascial release. Its textured surface stimulates blood circulation, reduces inflammation, and promotes faster muscle recovery after workouts. Ideal for athletes, runners, and fitness enthusiasts, this foam roller enhances flexibility and range of motion while preventing injuries. Lightweight and portable, it can be used at home, in the gym, or during travel."
    },
    {
      name: "Dip Station",
      category: "Gym Equipment",
      costInRupees: 3500,
      description: "A sturdy station for performing dips, leg raises, and other bodyweight exercises.",
      imageadd1: '/equipimages/Dip Station1.jpg',
      imageadd2: '/equipimages/Dip Station2.jpg',
      imageadd3: '/equipimages/Dip Station3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "The Dip Station is a versatile piece of gym equipment that allows you to perform a variety of upper-body and core exercises, including dips, leg raises, and push-ups. Its sturdy frame and padded grips provide stability and comfort during workouts, making it suitable for both beginners and advanced users. The adjustable height and wide base ensure proper form and support, helping you build strength in your chest, shoulders, triceps, and core muscles."
    },
    {
      name: "Elliptical Trainer",
      category: "Gym Equipment",
      costInRupees: 25000,
      description: "An elliptical machine for low-impact cardio workouts at home.",
      imageadd1: '/equipimages/Elliptical Trainer1.jpg',
      imageadd2: '/equipimages/Elliptical Trainer2.jpg',
      imageadd3: '/equipimages/Elliptical Trainer3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "The Elliptical Trainer offers a low-impact cardiovascular workout that simulates walking, running, and climbing stairs without stressing the joints. It provides a full-body workout, targeting muscles in the arms, legs, and core while improving cardiovascular endurance. With adjustable resistance levels and built-in workout programs, this machine is suitable for users of all fitness levels. Its compact design and smooth motion make it an excellent choice for home gyms, allowing you to achieve a challenging workout without leaving the house."
    },
    {
      name: "Weighted Vest",
      category: "Gym Equipment",
      costInRupees: 4000,
      description: "A vest with adjustable weights for adding resistance to bodyweight exercises.",
      imageadd1: '/equipimages/Weighted Vest1.jpg',
      imageadd2: '/equipimages/Weighted Vest2.jpg',
      imageadd3: '/equipimages/Weighted Vest3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "The Weighted Vest is designed to increase the intensity of bodyweight exercises by adding resistance. It features adjustable weight pockets distributed evenly across the vest, allowing you to customize the load from 5kg to 20kg or more. Ideal for calisthenics, running, hiking, or any exercise routine, the vest helps build strength, improve endurance, and burn more calories. Its ergonomic design ensures a snug fit and even weight distribution, making it comfortable to wear during intense workouts."
    },
    {
      name: "Gymnastic Rings",
      category: "Gym Equipment",
      costInRupees: 3000,
      description: "Wooden rings for performing gymnastic movements and bodyweight exercises.",
      imageadd1: '/equipimages/Gymnastic Rings1.jpg',
      imageadd2: '/equipimages/Gymnastic Rings2.jpg',
      imageadd3: '/equipimages/Gymnastic Rings3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Gymnastic Rings are versatile tools that allow for a wide range of exercises, including pull-ups, dips, muscle-ups, and core strengthening movements. Made from durable wooden rings with adjustable straps, they provide a challenging workout that improves strength, stability, and coordination. Ideal for gymnasts, calisthenics enthusiasts, and anyone looking to add variety to their workout routine, these rings can be easily set up indoors or outdoors for functional and dynamic training."
    },
    {
      name: "Cycling Gloves",
      category: "Gym Equipment",
      costInRupees: 500,
      description: "Padded gloves designed for comfort and grip during cycling workouts.",
      imageadd1: '/equipimages/Cycling Gloves1.jpg',
      imageadd2: '/equipimages/Cycling Gloves2.jpg',
      imageadd3: '/equipimages/Cycling Gloves3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Cycling Gloves are essential for cyclists, providing comfort, grip, and protection during long rides or indoor cycling sessions. They feature padded palms to absorb shock and reduce pressure on hands, enhancing comfort and preventing numbness. With breathable materials and adjustable closures, these gloves offer a snug fit and excellent ventilation, keeping hands cool and dry. Whether you're cycling for fitness, commuting, or competition, cycling gloves provide the support needed for a comfortable and enjoyable ride."
    },
    {
      name: "Power Tower",
      category: "Gym Equipment",
      costInRupees: 8000,
      description: "A multi-function tower for pull-ups, dips, leg raises, and push-ups.",
      imageadd1: '/equipimages/Power Tower1.jpg',
      imageadd2: '/equipimages/Power Tower2.jpg',
      imageadd3: '/equipimages/Power Tower3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "The Power Tower is a comprehensive fitness station that allows you to perform multiple upper-body and core exercises using your body weight. It includes pull-up bars, dip bars, push-up handles, and padded armrests for leg raises, offering a complete workout for strengthening the arms, shoulders, chest, back, and core muscles. Sturdy and stable, the power tower is suitable for home gyms or fitness centers, providing versatile exercise options for users of all fitness levels."
    },
    {
      name: "Boxing Gloves",
      category: "Gym Equipment",
      costInRupees: 1500,
      description: "Padded gloves for boxing training, sparring, and cardio workouts.",
      imageadd1: '/equipimages/Boxing Gloves1.jpg',
      imageadd2: '/equipimages/Boxing Gloves2.jpg',
      imageadd3: '/equipimages/Boxing Gloves3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Boxing Gloves are essential for boxing enthusiasts, providing protection, support, and comfort during training, sparring, or cardio workouts. They feature padding to absorb impact and protect hands while punching, ensuring safety and reducing the risk of injury. With breathable materials and adjustable wrist closures, boxing gloves offer a secure fit and ventilation, allowing for extended use without discomfort. Whether you're a beginner or experienced boxer, quality gloves are essential for maximizing performance and enjoyment."
    },
    {
      name: "Hydration Backpack",
      category: "Gym Equipment",
      costInRupees: 1200,
      description: "A backpack with a built-in hydration reservoir for hands-free water access.",
      imageadd1: '/equipimages/Hydration Backpack1.jpg',
      imageadd2: '/equipimages/Hydration Backpack2.jpg',
      imageadd3: '/equipimages/Hydration Backpack3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "A Hydration Backpack is designed for outdoor activities like hiking, running, cycling, and other sports where staying hydrated is crucial. It features a built-in hydration reservoir or bladder with a drinking tube, allowing you to carry water conveniently on your back. With additional storage compartments for essentials like keys, phone, and snacks, this backpack ensures you stay hydrated and fueled during long workouts or adventures. Lightweight and comfortable, it's a must-have for active individuals."
    },
    {
      name: "Battle Rope",
      category: "Gym Equipment",
      costInRupees: 2500,
      description: "A heavy-duty rope for high-intensity cardio and strength training.",
      imageadd1: '/equipimages/Battle Rope1.jpg',
      imageadd2: '/equipimages/Battle Rope2.jpg',
      imageadd3: '/equipimages/Battle Rope3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "The Battle Rope is a heavy-duty, durable rope that is ideal for high-intensity interval training (HIIT), cardio, and strength workouts. It's designed to improve grip strength, core stability, and cardiovascular endurance through dynamic movements like waves, slams, and spirals. Suitable for both indoor and outdoor use, the battle rope offers a challenging full-body workout that engages muscles from shoulders to legs. It's a versatile tool for athletes, fitness enthusiasts, and anyone looking to add intensity to their training regimen."
    },
    {
      name: "Suspension Yoga Swing",
      category: "Gym Equipment",
      costInRupees: 3500,
      description: "A swing set for aerial yoga and inversion therapy.",
      imageadd1: '/equipimages/Suspension Yoga Swing1.jpg',
      imageadd2: '/equipimages/Suspension Yoga Swing2.jpg',
      imageadd3: '/equipimages/Suspension Yoga Swing3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "The Suspension Yoga Swing allows you to practice aerial yoga, inversion therapy, and bodyweight exercises with ease. It supports various yoga poses, stretches, and decompression exercises, promoting flexibility, spinal alignment, and relaxation. Made from durable fabric with adjustable straps and handles, the swing set can be easily installed indoors or outdoors. It's suitable for beginners and experienced yogis alike, offering a unique way to improve balance, core strength, and overall well-being."
    },
    {
      name: "Adjustable Kettlebell",
      category: "Gym Equipment",
      costInRupees: 4000,
      description: "A kettlebell with adjustable weight plates for versatile strength training.",
      imageadd1: '/equipimages/Adjustable Kettlebell1.jpg',
      imageadd2: '/equipimages/Adjustable Kettlebell2.jpg',
      imageadd3: '/equipimages/Adjustable Kettlebell3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "The Adjustable Kettlebell combines the benefits of traditional kettlebell training with adjustable weight plates for customizable workouts. It allows you to quickly adjust the weight from lighter to heavier settings, making it suitable for beginners to advanced lifters. Ideal for swings, squats, presses, and other kettlebell exercises, this versatile tool helps build strength, power, and endurance. Its compact design and ergonomic handle provide comfort and stability during workouts, making it a valuable addition to any home gym."
    },
    {
      name: "Fitness Ball",
      category: "Gym Equipment",
      costInRupees: 1200,
      description: "A stability ball for core strengthening, balance, and flexibility exercises.",
      imageadd1: '/equipimages/Fitness Ball1.jpg',
      imageadd2: '/equipimages/Fitness Ball2.jpg',
      imageadd3: '/equipimages/Fitness Ball3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Fitness Ball, also known as stability ball or exercise ball, is versatile equipment for core strengthening, balance training, and flexibility exercises. It helps improve posture, stability, and coordination by engaging core muscles during workouts. Suitable for exercises like crunches, planks, and stretches, the fitness ball adds variety and challenge to your fitness routine. Made from durable anti-burst material with a textured surface for grip, it's suitable for users of all fitness levels and can be used at home, in the gym, or in rehabilitation settings."
    },
    {
      name: "Speed Rope",
      category: "Gym Equipment",
      costInRupees: 500,
      description: "A lightweight jump rope designed for speed and agility training.",
      imageadd1: '/equipimages/Speed Rope1.jpg',
      imageadd2: '/equipimages/Speed Rope2.jpg',
      imageadd3: '/equipimages/Speed Rope3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Speed Rope is a lightweight and durable jump rope designed for speed, agility, and cardiovascular training. Its ergonomic handles and smooth, fast-spinning rope allow for quick rotations and precise movements, making it ideal for double unders, crossovers, and intense cardio workouts. Adjustable length ensures a perfect fit for users of all heights. Compact and portable, the speed rope is perfect for home workouts, outdoor training, or taking to the gym, providing an effective way to improve coordination, endurance, and calorie burn."
    },
    {
      name: "Pull-Up Bar",
      category: "Gym Equipment",
      costInRupees: 1500,
      description: "A doorway pull-up bar for upper body strength and muscle development.",
      imageadd1: '/equipimages/Pull-Up Bar1.jpg',
      imageadd2: '/equipimages/Pull-Up Bar2.jpg',
      imageadd3: '/equipimages/Pull-Up Bar3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Pull-Up Bar is a doorway-mounted fitness equipment that allows for effective upper body workouts, including pull-ups, chin-ups, and hanging leg raises. It provides multiple grip positions for targeting different muscle groups, such as wide grip, narrow grip, and neutral grip. Easy to install and remove without drilling, the pull-up bar is suitable for home use and offers a convenient way to strengthen back, shoulders, arms, and core muscles. It's a versatile tool for building upper body strength and improving overall fitness."
    },
    {
      name: "Weightlifting Belt",
      category: "Gym Equipment",
      costInRupees: 1000,
      description: "A supportive belt for weightlifting, squats, and deadlifts.",
      imageadd1: '/equipimages/Weightlifting Belt1.jpg',
      imageadd2: '/equipimages/Weightlifting Belt2.jpg',
      imageadd3: '/equipimages/Weightlifting Belt3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Weightlifting Belt provides support and stability to the lower back and core muscles during heavy lifts, such as squats, deadlifts, and overhead presses. It helps maintain proper posture and prevents injury by reducing stress on the spine. Made from durable materials with adjustable closures, the weightlifting belt offers a snug fit and comfortable support, allowing you to lift heavier weights safely. It's essential for serious lifters and athletes who prioritize safety and performance in their strength training routines."
    },
    {
      name: "Pilates Ring",
      category: "Gym Equipment",
      costInRupees: 800,
      description: "A flexible ring for pilates, toning, and strengthening exercises.",
      imageadd1: '/equipimages/Pilates Ring1.jpg',
      imageadd2: '/equipimages/Pilates Ring2.jpg',
      imageadd3: '/equipimages/Pilates Ring3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Pilates Ring, also known as Magic Circle, is a versatile tool for pilates, toning, and strengthening exercises. It's designed to target specific muscle groups, including the inner and outer thighs, arms, and core. The flexible ring provides resistance to engage muscles and improve flexibility, making workouts more challenging and effective. Lightweight and portable, it can be used at home, in the gym, or during travel to enhance pilates routines and overall fitness."
    },
    {
      name: "Box Jump Platform",
      category: "Gym Equipment",
      costInRupees: 3000,
      description: "A sturdy platform for plyometric exercises and jump training.",
      imageadd1: '/equipimages/Box Jump Platform1.jpg',
      imageadd2: '/equipimages/Box Jump Platform2.jpg',
      imageadd3: '/equipimages/Box Jump Platform3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Box Jump Platform is a sturdy and stable platform used for plyometric exercises and jump training. It's designed to improve explosive power, agility, and vertical jump height by performing box jumps, step-ups, and other dynamic movements. The non-slip surface ensures safety and stability during intense workouts, making it suitable for athletes, CrossFit enthusiasts, and anyone looking to enhance their athletic performance. Adjustable height options allow for progressive training and challenge."
    },
    {
      name: "Squat Rack",
      category: "Gym Equipment",
      costInRupees: 10000,
      description: "A heavy-duty rack for squatting, bench pressing, and barbell exercises.",
      imageadd1: '/equipimages/Squat Rack1.jpg',
      imageadd2: '/equipimages/Squat Rack2.jpg',
      imageadd3: '/equipimages/Squat Rack3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Squat Rack is a heavy-duty gym equipment designed for strength training exercises like squats, bench presses, and barbell lifts. It provides a stable and secure platform for lifting heavy weights, allowing you to perform exercises safely and effectively. Adjustable height settings and safety catches ensure proper form and support during workouts, making it suitable for both home gyms and commercial fitness facilities. The squat rack is essential for serious lifters and strength training enthusiasts."
    },
    {
      name: "Gymnastics Mat",
      category: "Gym Equipment",
      costInRupees: 2500,
      description: "A padded mat for gymnastics, tumbling, and floor exercises.",
      imageadd1: '/equipimages/Gymnastics Mat1.jpg',
      imageadd2: '/equipimages/Gymnastics Mat2.jpg',
      imageadd3: '/equipimages/Gymnastics Mat3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Gymnastics Mat is a padded mat designed for gymnastics, tumbling, and floor exercises. It provides cushioning and shock absorption to reduce impact on joints and bones during landings and movements. The non-slip surface enhances grip and stability, ensuring safety during dynamic routines and skills practice. Lightweight and foldable, gymnastics mats are portable and easy to store, making them ideal for home practice, gymnastics classes, or recreational use."
    },
    {
      name: "Jump Box Set",
      category: "Gym Equipment",
      costInRupees: 3500,
      description: "A set of stackable boxes for plyometric training and jump exercises.",
      imageadd1: '/equipimages/Jump Box Set1.jpg',
      imageadd2: '/equipimages/Jump Box Set2.jpg',
      imageadd3: '/equipimages/Jump Box Set3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Jump Box Set includes stackable boxes of varying heights for plyometric training, jump exercises, and agility drills. It's designed to improve explosive power, speed, and coordination by performing box jumps, step-ups, and lateral movements. The sturdy construction and non-slip surface ensure safety and stability during intense workouts, making it suitable for athletes, fitness enthusiasts, and CrossFit practitioners. Adjustable height options allow for progressive training and challenge."
    },
    {
      name: "Calf Compression Sleeves",
      category: "Gym Equipment",
      costInRupees: 800,
      description: "Compression sleeves for calf muscle support and recovery.",
      imageadd1: '/equipimages/Calf Compression Sleeves1.jpg',
      imageadd2: '/equipimages/Calf Compression Sleeves2.jpg',
      imageadd3: '/equipimages/Calf Compression Sleeves3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Calf Compression Sleeves provide graduated compression to the calf muscles, promoting blood circulation, reducing muscle soreness, and speeding up recovery after workouts. They offer support and stability during running, cycling, and other high-impact activities, minimizing fatigue and preventing injuries like shin splints. Lightweight and breathable, compression sleeves can be worn during exercise or as recovery wear to enhance performance and maintain optimal leg health."
    },
    {
      name: "Resistance Loop Bands",
      category: "Gym Equipment",
      costInRupees: 500,
      description: "Loop bands for stretching, strength training, and physical therapy.",
      imageadd1: '/equipimages/Resistance Loop Bands1.jpg',
      imageadd2: '/equipimages/Resistance Loop Bands2.jpg',
      imageadd3: '/equipimages/Resistance Loop Bands3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Resistance Loop Bands are versatile tools for stretching, strength training, and physical therapy exercises. Available in different resistance levels, they can be used for various workouts targeting different muscle groups, including arms, legs, and glutes. Loop bands are lightweight, portable, and easy to use at home, in the gym, or while traveling. They help improve flexibility, build muscle strength, and enhance mobility, making them suitable for beginners and advanced fitness enthusiasts alike."
    },
    {
      name: "Rowing Machine",
      category: "Cardio Equipment",
      costInRupees: 30000,
      description: "A compact rowing machine for full-body cardio and strength workouts.",
      imageadd1: '/equipimages/Rowing Machine1.jpg',
      imageadd2: '/equipimages/Rowing Machine2.jpg',
      imageadd3: '/equipimages/Rowing Machine3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Rowing Machine is a versatile piece of cardio equipment that provides a full-body workout, targeting muscles in the arms, legs, back, and core. It simulates the motion of rowing on water, offering low-impact cardiovascular exercise with adjustable resistance levels. Ideal for improving endurance, strength, and cardiovascular health, the rowing machine features a comfortable seat, ergonomic handles, and a smooth gliding rail system. Its compact design allows for easy storage and use at home or in the gym."
    },
    {
      name: "Balance Board",
      category: "Balance Equipment",
      costInRupees: 1500,
      description: "A balance board for improving stability, coordination, and core strength.",
      imageadd1: '/equipimages/Balance Board1.jpg',
      imageadd2: '/equipimages/Balance Board2.jpg',
      imageadd3: '/equipimages/Balance Board3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Balance Board is a training tool designed to improve balance, coordination, and core strength. It features a sturdy platform with a non-slip surface that challenges users to maintain stability while performing exercises like squats, lunges, and twists. Suitable for athletes, rehab patients, and fitness enthusiasts, the balance board enhances proprioception and neuromuscular control. It's compact and portable, making it easy to use at home, in the gym, or during physical therapy sessions."
    },
    {
      name: "Adjustable Step Platform",
      category: "Gym Equipment",
      costInRupees: 2500,
      description: "A height-adjustable step platform for aerobic workouts and step exercises.",
      imageadd1: '/equipimages/Adjustable Step Platform1.jpg',
      imageadd2: '/equipimages/Adjustable Step Platform2.jpg',
      imageadd3: '/equipimages/Adjustable Step Platform3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Adjustable Step Platform is a versatile fitness tool for aerobic workouts, step exercises, and cardio conditioning. It features a height-adjustable platform with non-slip surface and removable risers, allowing users to customize the intensity of their workouts. Ideal for step aerobics, plyometrics, and circuit training, the step platform enhances cardiovascular fitness, leg strength, and coordination. Its compact design and lightweight construction make it suitable for home gyms, fitness classes, and personal training sessions."
    },
    {
      name: "Resistance Cable Set",
      category: "Gym Equipment",
      costInRupees: 1200,
      description: "A set of resistance cables with handles for strength training and mobility exercises.",
      imageadd1: '/equipimages/Resistance Cable Set1.jpg',
      imageadd2: '/equipimages/Resistance Cable Set2.jpg',
      imageadd3: '/equipimages/Resistance Cable Set3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Resistance Cable Set includes multiple resistance cables with ergonomic handles for strength training, rehabilitation, and mobility exercises. It offers variable resistance levels to target different muscle groups, from arms and shoulders to legs and core. Ideal for home workouts, travel, or gym sessions, resistance cables provide versatile exercise options such as bicep curls, chest presses, and leg extensions. Compact and portable, they are suitable for users of all fitness levels seeking effective and convenient strength training."
    },
    {
      name: "Plyometric Box",
      category: "Gym Equipment",
      costInRupees: 4000,
      description: "A sturdy box for plyometric training, jump exercises, and agility drills.",
      imageadd1: '/equipimages/Plyometric Box1.jpg',
      imageadd2: '/equipimages/Plyometric Box2.jpg',
      imageadd3: '/equipimages/Plyometric Box3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Plyometric Box is a sturdy platform used for plyometric training, jump exercises, and agility drills. It's designed to improve explosive power, speed, and coordination by performing box jumps, step-ups, and depth jumps. The non-slip surface ensures safety and stability during intense workouts, making it suitable for athletes, fitness enthusiasts, and CrossFit practitioners. Plyometric boxes come in various heights to accommodate different fitness levels and training goals."
    },
    {
      name: "Suspension Trainer",
      category: "Gym Equipment",
      costInRupees: 6000,
      description: "A suspension training system for bodyweight exercises and strength training.",
      imageadd1: '/equipimages/Suspension Trainer1.jpg',
      imageadd2: '/equipimages/Suspension Trainer2.jpg',
      imageadd3: '/equipimages/Suspension Trainer3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Suspension Trainer is a portable training system that uses bodyweight for resistance exercises targeting multiple muscle groups. It consists of adjustable straps with handles or foot cradles that can be anchored to a door, tree, or sturdy structure. Suitable for all fitness levels, suspension training enhances strength, flexibility, and core stability through exercises like rows, push-ups, and planks. Compact and lightweight, it's ideal for home workouts, outdoor fitness, or travel."
    },
    {
      name: "Magnetic Rowing Machine",
      category: "Cardio Equipment",
      costInRupees: 35000,
      description: "A magnetic resistance rowing machine for smooth and quiet indoor workouts.",
      imageadd1: '/equipimages/Magnetic Rowing Machine1.jpg',
      imageadd2: '/equipimages/Magnetic Rowing Machine2.jpg',
      imageadd3: '/equipimages/Magnetic Rowing Machine3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Magnetic Rowing Machine offers a smooth and quiet indoor workout experience using magnetic resistance technology. It simulates the natural motion of rowing on water, providing a full-body cardiovascular workout that engages muscles in the arms, legs, back, and core. Adjustable resistance levels and ergonomic design ensure a customizable and comfortable exercise session. Compact and foldable, the rowing machine is easy to store and suitable for home gyms or fitness enthusiasts looking for effective low-impact cardio."
    },
    {
      name: "Fitness Ball Chair",
      category: "Office Equipment",
      costInRupees: 3000,
      description: "A stability ball integrated into an ergonomic chair for active sitting.",
      imageadd1: '/equipimages/Fitness Ball Chair1.jpg',
      imageadd2: '/equipimages/Fitness Ball Chair2.jpg',
      imageadd3: '/equipimages/Fitness Ball Chair3.jpg',
      rating: 3.5,
      discount: 54,
      isCart: false,
      longDescription: "Fitness Ball Chair combines the benefits of a stability ball with an ergonomic chair design for active sitting. It promotes better posture, core engagement, and spine alignment while sitting at a desk or workstation. The stability ball base provides dynamic support and encourages subtle movements to improve balance and circulation throughout the day. Adjustable height and back support ensure comfort and proper alignment, making it ideal for office use or home office setups."
    }
];